const products = [
  {
    id: 1,
    name: "Bandeja Paisa",
    type: "Food & Restaurants",
    price: 15,
    group: "food",
    img: "",
  },
  {
    id: 2,
    name: "Arepas",
    type: "Food & Restaurants",
    price: 8,
    group: "food",
    img: "",
  },
  {
    id: 3,
    name: "Ajiaco",
    type: "Food & Restaurants",
    price: 30,
    group: "food",
    img: "",
  },
  {
    id: 4,
    name: "Fried Fish",
    type: "Food & Restaurants",
    price: 15,
    group: "food",
    img: "",
  },
  {
    id: 5,
    name: "Shrimp Ceviche",
    type: "Food & Restaurants",
    price: 30,
    group: "food",
    img: "",
  },
  {
    id: 6,
    name: "bean casserole",
    type: "Food & Restaurants",
    price: 25,
    group: "food",
    img: "",
  },
  {
    id: 7,
    name: "Multivitamins",
    type: "Pharmacy & Wellness",
    price: 25,
    group: "pharmacy",
    img: "",
  },
  {
    id: 8,
    name: "Vitamin D",
    type: "Pharmacy & Wellness",
    price: 20,
    group: "pharmacy",
    img: "",
  },
  {
    id: 9,
    name: "Magnesium",
    type: "Pharmacy & Wellness",
    price: 30,
    group: "pharmacy",
    img: "",
  },
  {
    id: 10,
    name: "Collagen",
    type: "Pharmacy & Wellness",
    price: 50,
    group: "pharmacy",
    img: "",
  },
  {
    id: 11,
    name: "Probiotics",
    type: "Pharmacy & Wellness",
    price: 25,
    group: "pharmacy",
    img: "",
  },
  {
    id: 12,
    name: "Melatonin",
    type: "Pharmacy & Wellness",
    price: 30,
    group: "pharmacy",
    img: "",
  },
  {
    id: 13,
    name: "Rice",
    type: "Groceries & Drinks",
    price: 2,
    group: "gorceries",
    img: "",
  },
  {
    id: 14,
    name: "Orange",
    type: "Groceries & Drinks",
    price: 3,
    group: "gorceries",
    img: "",
  },
  {
    id: 15,
    name: "Eggs",
    type: "Groceries & Drinks",
    price: 6,
    group: "gorceries",
    img: "",
  },
  {
    id: 16,
    name: "Tomatoes",
    type: "Groceries & Drinks",
    price: 3,
    group: "gorceries",
    img: "",
  },
  {
    id: 17,
    name: "Strawberries",
    type: "Groceries & Drinks",
    price: 3,
    group: "gorceries",
    img: "",
  },
  {
    id: 18,
    name: "Bread",
    type: "Groceries & Drinks",
    price: 3,
    group: "gorceries",
    img: "",
  },
];
